[colors]
ansi = [
    "#090618",
    "#c34043",
    "#76946a",
    "#c0a36e",
    "#7e9cd8",
    "#957fb8",
    "#6a9589",
    "#c8c093",
]
background = "#1f1f28"
brights = [
    "#727169",
    "#e82424",
    "#98bb6c",
    "#e6c384",
    "#7fb4ca",
    "#938aa9",
    "#7aa89f",
    "#dcd7ba",
]
compose_cursor = "#c8c093"
cursor_bg = "#c8c093"
cursor_border = "#c8c093"
cursor_fg = "#1f1f28"
foreground = "#dcd7ba"
scrollbar_thumb = "#2d4f67"
selection_bg = "#2d4f67"
selection_fg = "#c8c093"
split = "#727169"
visual_bell = "#090618"

[colors.indexed]
16 = "#c0a36e"
17 = "#c8c093"

[colors.tab_bar]
background = "#1b1b24"
inactive_tab_edge = "#2d4f67"

[colors.tab_bar.active_tab]
bg_color = "#76946a"
fg_color = "#1f1f28"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#1d1d26"
fg_color = "#dcd7ba"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1f1f28"
fg_color = "#dcd7ba"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#2d4f67"
fg_color = "#dcd7ba"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#727169"
fg_color = "#dcd7ba"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "Noctalia"
name = "Noctalia"
